# Generated by Django 5.0.6 on 2024-07-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ID_Producto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre_Produc', models.CharField(max_length=50)),
                ('Descripción', models.CharField(max_length=50)),
            ],
        ),
    ]
