# Generated by Django 5.0.6 on 2024-07-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_categoría_precio_supermercado_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precio',
            name='Fecha_registro',
        ),
        migrations.AlterField(
            model_name='categoría',
            name='ID_Categoría',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='precio',
            name='ID_Precio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='precio',
            name='Precio_Prod',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ID_Producto',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Nombre_Produc',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre Producto'),
        ),
        migrations.AlterField(
            model_name='supermercado',
            name='ID_Supermercado',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Correo',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Fechar_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ID_Usuario',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Nombre_User',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre de Usuario'),
        ),
    ]
